const dogData = [
  {
    image: "images/murphy-card.jpg",
    name: "Murphy",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/poppy-card.jpg",
    name: "Poppy",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/jack-card.jpg",
    name: "Jack",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/duffy-card.jpg",
    name: "Duffy",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/lucas-card.jpg",
    name: "Lucas",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/jake-card.jpg",
    name: "Jake",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/angus-card.jpg",
    name: "Angus",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/violet-card.jpg",
    name: "Violet",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/piper-card.jpg",
    name: "Piper",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/maximus-card.jpg",
    name: "Maximus",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/luna-card.jpg",
    name: "Luna",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
  {
    image: "images/stella-card.jpg",
    name: "Stella",
    fee: "123.45",
    info: "Corrum volorit iandae nimaxim cum restia volor reicid ut et etur sunt arum rendae pla endis re ea erum, quidoluptae",
    breed: "To be announced",
  },
];
